# file: roles/s3fs/tasks/main.yml
---

  - shell: "s3fs"
    register: has_s3
    ignore_errors: True

  - name: install prequisites
    sudo: yes
    apt: pkg="{{ item }}" state="present"
    with_items:
      - build-essential
      - libfuse-dev
      - libcurl4-openssl-dev
      - libxml2-dev
      - mime-support
      - unzip
      - autoconf
    when: has_s3|failed
      
  - name: copy src & password
    copy: "{{ item }}"
    with_items:
      - src=../files/s3fs-{{ s3fs_version }}.zip dest=/tmp mode=0644
      - src={{ s3fs_aws_key }}  dest=/etc mode=400
    when: has_s3|failed
    
  - name: extract
    command: chdir=/tmp unzip -qo /tmp/s3fs-{{ s3fs_version }}.zip
    when: has_s3|failed

  - name: configure & build
    sudo: yes
    command: "{{ item }} chdir='/tmp/s3fs-fuse-master'"
    with_items:
      - autoreconf --install
      - ./configure --prefix=/usr
      - make
      - make install
    when: has_s3|failed

  - name: create mount point
    sudo: yes
    file: path=/mnt/{{ item.mount }} state=directory
    when: has_s3|failed
    with_items: s3fs_mounts
    
  - name: mount the bucket
    sudo: yes
    command: s3fs {{ item.bucket }} -o use_cache=/tmp -o allow_other /mnt/{{ item.mount }}
    when: has_s3|failed
    with_items: s3fs_mounts
    